export const enum ActionTypes {
  SELECT_ARTIST = "SELECT_ARTIST",
  DESELECT_ARTIST = "DESELECT_ARTIST",
  RESET_SELECTION = "RESET_SELECTION",
  SET_RETIRED = "SET_RETIRED",
  SET_NOT_RETIRED = "SET_NOT_RETIRED",
}
