export const enum ActionTypes {
  SEARCH_ARTISTS = "SEARCH_ARTISTS",
  CREATE_ARTIST = "CREATE_ARTIST",
  FIND_ARTIST = "FIND_ARTIST",
  RESET_ARTIST = "RESET_ARTIST",
  DELETE_ARTIST = "DELETE_ARTIST",
  EDIT_ARTIST = "EDIT_ARTIST",
  REFRESH_SEARCH = "REFRESH_SEARCH",
}
